# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 06 Nov 2008 23:21:38 +0100
*	@ALL	1
*	@moderator	16
bbob-2009-downloads	@ALL	1
bbob-2009-downloads	@moderator	2
bbob-2009-uploads	@ALL	0
bbob-2009-uploads	@moderator	0
bbob-2010-downloads	@ALL	1
bbob-2010-downloads	@moderator	2
bbob-2010-uploads	@ALL	0
bbob-2010-uploads	@uploader	1
bbob-2010-uploads	@moderator	2
bbob-2012-uploads	@uploader	1
bbob-2012-uploads	@ALL	0
bbob-2012-uploads	@moderator	2
downloadsbeta	@ALL	0
downloadsbeta	@moderator	2
downloadsbeta	@betatester	1
playground:*	@user	1
playground:*	@ALL	0
playground:*	@moderator	2
playground:playground	@ALL	1
test	@ALL	0
test	@moderator	2
test-uploads	@ALL	0
test-uploads	@moderator	2
uploads	@uploader	1
uploads	@ALL	1
uploads	@moderator	2
uploads	@user	1
