# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 08 Sep 2016 15:21:46 +0000
*               @ALL          1
*               @user         8
